All:
	gcc -Iinclude/ src/speed.c src/app.c src/camera.c src/main.c src/scene.c src/floor.c src/texture.c src/utils.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lobj -lopengl32 -lm -o trainstation2.exe -Wall -Wextra -Wpedantic
