
All:
	gcc -Iinclude/ src/view.c src/window.c src/lamp.c src/cylinder.c src/man.c src/door.c src/train.c src/speed.c src/app.c src/camera.c src/main.c src/scene.c src/traintrack.c src/floor.c src/skybox.c src/tunnel.c src/tunnel_end.c src/texture.c src/utils.c  -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lobj -lopengl32 -lm -o station.exe -Wall -Wextra -Wpedantic

